In [1]:
import torch
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [4]:
%%time
start_time = time.time()
# matrix operation
zeros = torch.zeros(1, 1)
end_times = time.time()

elapsed_time = end_times - start_time
print(f'{elapsed_time: .4f}')

 0.0002
CPU times: user 150 μs, sys: 156 μs, total: 306 μs
Wall time: 247 μs


In [3]:
torch_rand1 = torch.rand (10000, 10000). to(device)
torch_rand2 = torch. rand (10000, 10000). to(device)
np_rand1 = torch. rand (10000, 10000)
np_rand2 = torch. rand (10000, 10000)

start_time - time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time. time()
elapsed_time = end_time - start_time
print(f" {elapsed_time:.8f}")

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time. time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

 285.44806790
0.29612327


/var/folders/z0/t_vv9z0908vc5j6k_b12pwn40000gp/T/ipykernel_41068/2789233944.py:14: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  rand = np.multiply(np_rand1, np_rand2)


In [6]:
# Define a probability tensor
probabilities = torch.tensor([0.1, 0.9])
# 10% or 01 => o, 90%Z or 0.9 >= 1, each probability points to the index of the probabilities
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
samples

tensor([1, 1, 0, 1, 1, 1, 0, 1, 1, 0])

In [7]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [8]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])