In [1]:
import torch
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [2]:
%%time
start_time = time.time()
# matrix operation
zeros = torch.zeros(1, 1)
end_times = time.time()

elapsed_time = end_times - start_time
print(f'{elapsed_time: .4f}')

 0.0007
CPU times: user 549 μs, sys: 928 μs, total: 1.48 ms
Wall time: 734 μs


In [3]:
torch_rand1 = torch.rand (10000, 10000). to(device)
torch_rand2 = torch. rand (10000, 10000). to(device)
np_rand1 = torch. rand (10000, 10000)
np_rand2 = torch. rand (10000, 10000)

start_time - time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time. time()
elapsed_time = end_time - start_time
print(f" {elapsed_time:.8f}")

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time. time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

 3.92982793
0.30731297


/var/folders/z0/t_vv9z0908vc5j6k_b12pwn40000gp/T/ipykernel_58807/2431387505.py:16: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  rand = np.multiply(np_rand1, np_rand2)


In [4]:
# Define a probability tensor
probabilities = torch.tensor([0.1, 0.9])
# 10% or 01 => o, 90%Z or 0.9 >= 1, each probability points to the index of the probabilities
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
samples

tensor([1, 1, 1, 0, 1, 1, 1, 1, 1, 1])

In [5]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [6]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [7]:
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [8]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [9]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [10]:
input = torch.zeros(2, 3, 4)
out = input.transpose(0, 2)
out.shape

torch.Size([4, 3, 2])

In [12]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

# Stack the tensors along a new dimension
# for making a batch
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [14]:
import torch.nn as nn
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)
linear(sample)

tensor([-2.3420, -1.6667,  7.3379], grad_fn=<SqueezeBackward4>)

In [15]:
import torch.nn.functional as F

# creaet a tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0])

# apply softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)
softmax_output

tensor([0.0900, 0.2447, 0.6652])

In [3]:
import torch.nn as nn

# Init an e,bedding layer
vocab_size = 10000
embedding_dim = 100
embedding = nn.Embedding(vocab_size, embedding_dim)

# Create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# Apply the embedding layer
embedded_output = embedding(input_indices)

embedded_output.shape
embedded_output

tensor([[ 1.2392e-02, -2.2733e-01, -3.5570e-02,  4.7562e-01,  9.7112e-02,
         -1.1432e-01, -4.5738e-02, -7.8960e-01,  1.1023e+00,  1.0629e+00,
          7.4582e-01, -3.8858e-01,  6.2158e-01,  6.3190e-01,  1.3257e+00,
         -1.5781e+00,  2.1670e-01, -1.2007e+00, -2.1351e+00,  8.6810e-01,
         -2.5998e+00,  1.1835e+00,  9.0926e-01,  7.0172e-02,  4.6598e-01,
          4.1228e-01,  1.5461e+00,  7.8193e-01,  1.4526e+00,  6.4001e-02,
          2.7878e-01,  1.1129e+00, -1.9279e+00, -4.7179e-01, -3.1902e-01,
         -2.4666e-01,  1.7344e-01, -1.1868e+00, -5.5780e-01,  3.0558e-01,
          4.3536e-01, -4.0269e-01, -2.5566e-01,  6.1353e-01, -3.4934e-01,
          4.1904e-01, -3.2398e-01,  2.7438e-01, -1.5872e-01, -1.4400e+00,
         -1.3510e+00,  2.1920e-01,  5.4590e-01,  6.1447e-01, -3.5899e-01,
         -9.1615e-01, -6.8322e-01, -2.8986e-01, -5.7049e-01, -1.3215e+00,
          1.8155e-02,  9.4294e-01,  2.8181e-01, -5.8216e-01,  3.3327e-01,
          1.5380e-01, -1.6047e+00, -1.

In [18]:
# Matrix Multiplication
a = torch.tensor([[1, 2], [3, 4], [5, 6]])
b = torch.tensor([[7, 8, 9], [10, 11, 12]])
# dot product
a @ b

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [22]:
#type int64
int_64 = torch.randint(1, (3, 2)).float()
#type float32
float_32 = torch.rand(2, 3)
int_64.dtype
result = torch.matmul(int_64, float_32)
result


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [4]:
a = torch.rand(2, 3, 5)
# unpack the torch tensor
x, y, z = a.shape
a = a.view(x, y, z)
a.shape

torch.Size([2, 3, 5])