In [1]:
import torch
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [2]:
%%time
start_time = time.time()
# matrix operation
zeros = torch.zeros(1, 1)
end_times = time.time()

elapsed_time = end_times - start_time
print(f'{elapsed_time: .4f}')

 0.0048
CPU times: user 1.18 ms, sys: 2.85 ms, total: 4.03 ms
Wall time: 5.01 ms


In [3]:
torch_rand1 = torch.rand (10000, 10000). to(device)
torch_rand2 = torch.rand (10000, 10000). to(device)
np_rand1 = torch.rand (10000, 10000)
np_rand2 = torch.rand (10000, 10000)

start_time - time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time. time()
elapsed_time = end_time - start_time
print(f" {elapsed_time:.8f}")

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time. time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

 2.95683312
0.30720401


/var/folders/z0/t_vv9z0908vc5j6k_b12pwn40000gp/T/ipykernel_93332/2337744327.py:16: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  rand = np.multiply(np_rand1, np_rand2)


In [4]:
# Define a probability tensor
probabilities = torch.tensor([0.1, 0.9])
# 10% or 01 => o, 90%Z or 0.9 >= 1, each probability points to the index of the probabilities
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
samples

tensor([1, 1, 1, 1, 1, 1, 1, 0, 0, 1])

In [5]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [6]:
# tril is making a triangular shape of matrix with 1 and 0
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [7]:
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [8]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [9]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [10]:
input = torch.zeros(2, 3, 4)
out = input.transpose(0, 2)
out.shape

torch.Size([4, 3, 2])

In [11]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

# Stack the tensors along a new dimension
# for making a batch
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [12]:
import torch.nn as nn
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)
linear(sample)

tensor([ 7.3072,  7.2185, 12.9880], grad_fn=<SqueezeBackward4>)

In [13]:
import torch.nn.functional as F

# creaet a tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0])

# apply softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)
softmax_output

tensor([0.0900, 0.2447, 0.6652])

In [14]:
import torch.nn as nn

# Init an e,bedding layer
vocab_size = 10000
embedding_dim = 100
embedding = nn.Embedding(vocab_size, embedding_dim)

# Create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# Apply the embedding layer
embedded_output = embedding(input_indices)

embedded_output.shape
embedded_output

tensor([[ 2.2337e+00, -2.0857e-01, -1.5413e+00, -4.8479e-02, -1.0044e+00,
          2.6424e-01,  7.9775e-02,  1.2979e+00,  3.6312e-01, -1.0739e+00,
         -1.1457e-01,  2.8456e-01, -3.5305e-01, -1.1540e+00,  5.7164e-01,
         -1.2368e+00, -2.9870e-01, -7.5536e-01,  1.7297e-01,  1.7439e+00,
          1.4931e+00, -9.5080e-01, -1.4705e+00,  1.1278e+00,  6.8075e-02,
          1.1210e+00, -1.0760e+00,  2.9613e-01,  8.1302e-01,  2.0347e+00,
          3.8288e-01, -1.3196e+00,  2.4115e-01,  1.0808e+00, -5.1086e-01,
          7.5798e-01, -2.0893e+00, -2.1838e-01, -5.7255e-01,  1.1455e+00,
          1.1028e+00, -9.4393e-01, -3.6049e-02,  2.2471e-01,  6.6789e-01,
         -8.9218e-01, -7.1831e-01, -1.1316e+00, -6.7330e-01, -9.4591e-01,
          1.5059e+00, -3.6210e-01, -3.6247e-01, -5.4153e-01, -6.4393e-01,
          8.0983e-02, -5.4664e-01, -1.4545e-01,  1.0338e+00, -2.1298e+00,
          6.5314e-01,  8.2233e-01,  8.5134e-01,  4.2356e-01, -4.0796e-01,
         -1.1059e+00,  8.1191e-02,  8.

In [15]:
# Matrix Multiplication
a = torch.tensor([[1, 2], [3, 4], [5, 6]])
b = torch.tensor([[7, 8, 9], [10, 11, 12]])
# dot product
a @ b

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [16]:
#type int64
int_64 = torch.randint(1, (3, 2)).float()
#type float32
float_32 = torch.rand(2, 3)
int_64.dtype
result = torch.matmul(int_64, float_32)
result


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [17]:
a = torch.rand(2, 3, 5)
# unpack the torch tensor
x, y, z = a.shape
a = a.view(x, y, z)
a.shape

torch.Size([2, 3, 5])